import { NextResponse } from 'next/server'
import bcrypt from 'bcryptjs'
import connectDB from '@/lib/mongodb'
import { User, Note, Question } from '@/models/index'

// ─────────────────────────────────────────────────────────────
// VISIT: https://your-site.vercel.app/api/setup-all
// Creates: Admin account + 25 notes + 30 questions
// Safe to run multiple times — skips existing data
// DELETE this file from GitHub after first use!
// ─────────────────────────────────────────────────────────────

const NOTES = [
  // ══════════════════ CLASS XII — PYTHON ══════════════════
  {
    title:'Functions in Python — Complete Guide',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'Functions',
    difficulty:'Basic', order:1, isPublished:true,
    content:`## What is a Function?\nA **function** is a named block of code that performs a specific task. Define once, call anywhere.\n\n## Types of Functions\n\n### 1. Built-in Functions\nAlready in Python — no import needed.\nExamples: \`print()\`, \`len()\`, \`input()\`, \`range()\`, \`int()\`, \`str()\`, \`max()\`, \`min()\`\n\n### 2. Functions in Modules\nNeed import first.\nExamples: \`math.sqrt()\`, \`random.randint()\`\n\n### 3. User Defined Functions\nCreated by you using \`def\` keyword.\n\n## Parameters vs Arguments\n- **Parameter** — variable in definition: \`def greet(name):\` — name is parameter\n- **Argument** — actual value when calling: \`greet("Rahul")\` — Rahul is argument\n\n## Scope of Variables\n- **Local Scope** — variable inside function, only available inside it\n- **Global Scope** — variable outside all functions, available everywhere\n- Use \`global\` keyword to modify a global variable inside a function\n\n## Default Parameters\nGive a parameter a preset value. Used when caller does not pass it.\nDefault parameters must come AFTER required ones.\n\n## Flow of Execution\n1. Program starts from top\n2. Function is called → control jumps to function body\n3. Function executes\n4. Control returns to where it was called`,
    syntax:`# Built-in function\nprint(len("Hello"))  # 5\n\n# Module function\nimport math\nprint(math.sqrt(16))  # 4.0\n\n# Simple user defined function\ndef greet(name):\n    message = "Hello, " + name + "!"\n    return message\n\nprint(greet("Rahul"))  # Hello, Rahul!\n\n# Default parameter\ndef power(base, exp=2):\n    return base ** exp\n\nprint(power(3))      # 9  (exp=2 by default)\nprint(power(3, 3))   # 27\n\n# Multiple return values\ndef min_max(numbers):\n    return min(numbers), max(numbers)\n\nlow, high = min_max([3, 1, 7, 2, 9])\nprint(low, high)  # 1 9\n\n# Global variable example\ncount = 0\ndef increment():\n    global count\n    count += 1\nincrement()\nprint(count)  # 1`,
    keyPoints:['def keyword defines a function','Parameters in definition, Arguments in calling','Default parameters must come AFTER required ones','Without return statement, function returns None','Local variables exist only inside the function','Use global keyword to modify global variables inside function'],
    tips:['Name functions with lowercase_underscores: calculate_area()','One function should do ONE thing only','Test with multiple different inputs','Functions longer than 20 lines should be split into smaller ones'],
    commonMistakes:['Calling function before defining it causes NameError','Forgetting return statement — function returns None','Default param before required param causes SyntaxError','Modifying global variable without global keyword'],
  },
  {
    title:'Exception Handling — try except finally else',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'Exception Handling',
    difficulty:'Intermediate', order:2, isPublished:true,
    content:`## What is an Exception?\nAn error that occurs during program execution (runtime). Python **raises** it. If unhandled — program **crashes**.\n\n## Common Exception Types\n\n| Exception | When It Occurs |\n|-----------|----------------|\n| ZeroDivisionError | Division by zero |\n| FileNotFoundError | File does not exist |\n| ValueError | Wrong value type: int("abc") |\n| TypeError | Wrong data type |\n| IndexError | List index out of range |\n| KeyError | Dictionary key not found |\n| NameError | Variable not defined |\n\n## Syntax\n\`\`\`python\ntry:\n    risky code here\nexcept ExceptionName:\n    handle the error\nelse:\n    runs ONLY if no exception\nfinally:\n    ALWAYS runs no matter what\n\`\`\`\n\n## The finally Block\nAlways runs — with or without exception.\nUse for **cleanup**: closing files, closing database connections.`,
    syntax:`# Basic exception handling\ntry:\n    num = int(input("Enter number: "))\n    result = 100 / num\n    print("Result:", result)\nexcept ZeroDivisionError:\n    print("Cannot divide by zero!")\nexcept ValueError:\n    print("Please enter a valid number!")\nfinally:\n    print("Program finished.")  # always runs\n\n# else block — runs only if NO exception\ntry:\n    x = int("42")\nexcept ValueError:\n    print("Not a number")\nelse:\n    print("Converted successfully:", x)\n\n# Capture error message\ntry:\n    open("missing_file.txt")\nexcept FileNotFoundError as e:\n    print("Error:", e)\n\n# Multiple exceptions at once\ntry:\n    data = [1, 2, 3]\n    print(data[10])\nexcept (IndexError, TypeError) as e:\n    print("Error occurred:", e)`,
    keyPoints:['try block contains the risky code','except block handles specific exceptions','finally ALWAYS runs — perfect for cleanup','else block runs ONLY when no exception occurred','"as e" captures the error message','Can have multiple except blocks for different exceptions'],
    tips:['Always catch specific exceptions, not bare except:','Use finally to close files or connections','Never use empty except: — it hides all bugs','Always print the error message when debugging'],
    commonMistakes:['Writing except before try — SyntaxError','Using bare except: catches everything including KeyboardInterrupt','Forgetting that finally runs even after return statement','Not printing error message makes debugging very hard'],
  },
  {
    title:'Text File Handling — All Modes and Methods',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'Text File Handling',
    difficulty:'Intermediate', order:3, isPublished:true,
    content:`## Why Files?\nFiles store data **permanently** on disk. Without files, all data is lost when program ends.\n\n## File Opening Modes\n\n| Mode | Behavior |\n|------|----------|\n| r | Read only. File must exist. Default. |\n| w | Write. Creates new OR overwrites existing. |\n| a | Append. Adds to end. Creates if not exists. |\n| r+ | Read and Write. File must exist. |\n| w+ | Write and Read. Creates or overwrites. |\n| a+ | Append and Read. |\n\n## Key Methods\n\n| Method | What it does |\n|--------|--------------|\n| write(str) | Write a string to file |\n| writelines(list) | Write a list of strings |\n| read() | Read entire file as one string |\n| readline() | Read exactly one line |\n| readlines() | Read all lines, returns a list |\n| seek(n) | Move pointer to position n |\n| tell() | Returns current pointer position |\n\n## Best Practice — with Statement\nAlways use \`with open()\` — auto-closes file even if error occurs.`,
    syntax:`# Write to file\nwith open("notes.txt", "w") as f:\n    f.write("Python is fun\\n")\n    f.write("File handling is easy\\n")\n\n# Append to file\nwith open("notes.txt", "a") as f:\n    f.write("Exceptions are important\\n")\n\n# Read entire file\nwith open("notes.txt", "r") as f:\n    content = f.read()\n    print(content)\n\n# Read line by line (best for large files)\nwith open("notes.txt", "r") as f:\n    for line in f:\n        print(line.strip())  # strip removes \\n\n\n# readlines() — returns list\nwith open("notes.txt", "r") as f:\n    lines = f.readlines()\n    print(lines)  # ['Python is fun\\n', ...]\n\n# Print each word separated by #\nwith open("notes.txt", "r") as f:\n    for line in f:\n        words = line.strip().split()\n        print("#".join(words))\n\n# Count vowels in file\nwith open("notes.txt", "r") as f:\n    text = f.read().lower()\n    vowels = sum(1 for c in text if c in 'aeiou')\n    print("Vowels:", vowels)\n\n# seek and tell\nwith open("notes.txt", "r") as f:\n    f.seek(5)          # move to position 5\n    print(f.tell())    # prints 5\n    print(f.read(10))  # read 10 chars from position 5\n\n# writelines — write a list\nstudents = ["Rahul\\n", "Priya\\n", "Amit\\n"]\nwith open("students.txt", "w") as f:\n    f.writelines(students)`,
    keyPoints:['"w" mode DELETES existing content — be very careful!','"a" mode safely adds to end without deleting','Always use with open() — it auto-closes the file','readline() includes \\n — always use .strip() to remove it','readlines() returns a list — each element is one line with \\n','seek(0) moves pointer back to the start of file'],
    tips:['Test with "r" mode first before writing','Always strip() each line to remove trailing \\n','"a" mode when adding data to existing file','Check if file exists with os.path.exists() before reading'],
    commonMistakes:['Using "w" instead of "a" — accidentally deletes all data!','Forgetting \\n in write() — all text on same line','Not stripping \\n from readline() output','Opening in "r" mode when file does not exist — FileNotFoundError'],
  },
  {
    title:'Binary File Handling — pickle module dump and load',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'Binary File Handling',
    difficulty:'Intermediate', order:4, isPublished:true,
    content:`## What is a Binary File?\nStores data in **binary format** — not human readable. Used to store Python objects directly.\n\n## The pickle Module\n\n| Function | Use |\n|----------|-----|\n| pickle.dump(obj, file) | Write Python object to binary file |\n| pickle.load(file) | Read Python object from binary file |\n\n## Binary File Modes\n| Mode | Use |\n|------|-----|\n| wb | Write binary — creates/overwrites |\n| rb | Read binary |\n| ab | Append binary |\n\n## How it Works\n- **dump()** = serializes (Python object → binary bytes) → writes to file\n- **load()** = reads bytes → deserializes → returns Python object back\n\n## Update Strategy\nTo update a binary file:\n1. Load all records\n2. Modify in memory\n3. Dump all back to file`,
    syntax:`import pickle\n\n# Write (dump) data\nstudents = [\n    {"roll": 1, "name": "Rahul", "marks": 85},\n    {"roll": 2, "name": "Priya", "marks": 92},\n    {"roll": 3, "name": "Amit",  "marks": 78},\n]\nwith open("students.dat", "wb") as f:\n    pickle.dump(students, f)\nprint("Data saved!")\n\n# Read (load) data\nwith open("students.dat", "rb") as f:\n    data = pickle.load(f)\nprint(data)\n\n# Search by roll number\ndef search_student(roll_no):\n    with open("students.dat", "rb") as f:\n        records = pickle.load(f)\n    for s in records:\n        if s["roll"] == roll_no:\n            print("Found:", s["name"], "Marks:", s["marks"])\n            return\n    print("Roll number not found!")\n\nsearch_student(2)  # Found: Priya Marks: 92\n\n# Update marks\ndef update_marks(roll_no, new_marks):\n    with open("students.dat", "rb") as f:\n        records = pickle.load(f)\n    for s in records:\n        if s["roll"] == roll_no:\n            s["marks"] = new_marks\n    with open("students.dat", "wb") as f:\n        pickle.dump(records, f)\n    print("Updated!")\n\nupdate_marks(1, 90)\n\n# Add new record\ndef add_student(new_student):\n    with open("students.dat", "rb") as f:\n        records = pickle.load(f)\n    records.append(new_student)\n    with open("students.dat", "wb") as f:\n        pickle.dump(records, f)\n\nadd_student({"roll": 4, "name": "Sneha", "marks": 88})`,
    keyPoints:['import pickle required before using dump or load','dump() writes Python object to binary file','load() reads and returns the Python object','File must be opened in binary mode: wb or rb','To update: load all → modify in memory → dump all back','Binary files are NOT human readable — cannot open in Notepad'],
    tips:['Use .dat or .bin extension for binary files','Always read first, modify, then write back','Use try-except for EOFError when reading might-be-empty file','pickle can store any Python object: dict, list, class instance'],
    commonMistakes:['Opening binary file in text mode "r" instead of "rb"','Forgetting import pickle','Using "ab" incorrectly with pickle — use load+dump approach','Trying to open .dat file in Notepad to check data'],
  },
  {
    title:'CSV File Handling — csv module writerow reader',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'CSV File Handling',
    difficulty:'Intermediate', order:5, isPublished:true,
    content:`## What is CSV?\n**Comma Separated Values** — plain text, each value separated by comma. Opens in Excel.\n\nExample CSV content:\n\`\`\`\nrollno,name,marks,city\n1,Rahul Sharma,85,Unchahar\n2,Priya Singh,92,Raebareli\n\`\`\`\n\n## csv Module Functions\n\n| Function | Use |\n|----------|-----|\n| csv.writer(file) | Create writer object |\n| writer.writerow(list) | Write ONE row |\n| writer.writerows(list_of_lists) | Write MULTIPLE rows at once |\n| csv.reader(file) | Create reader object |\n\n## Important Rule\nAlways use \`newline=""\` when opening CSV for writing — prevents extra blank lines between rows.`,
    syntax:`import csv\n\n# Writing CSV\nwith open("students.csv", "w", newline="") as f:\n    writer = csv.writer(f)\n    writer.writerow(["rollno", "name", "marks", "city"])  # header\n    writer.writerow([1, "Rahul Sharma", 85, "Unchahar"])\n    writer.writerow([2, "Priya Singh",  92, "Raebareli"])\n\n# writerows — write multiple rows at once\nmore_data = [\n    [3, "Amit Kumar",  78, "Lucknow"],\n    [4, "Sneha Gupta", 88, "Allahabad"],\n]\nwith open("students.csv", "a", newline="") as f:\n    writer = csv.writer(f)\n    writer.writerows(more_data)\n\n# Reading CSV\nwith open("students.csv", "r") as f:\n    reader = csv.reader(f)\n    for row in reader:\n        print(row)  # each row is a list: ['1','Rahul',…]\n\n# Skip header row when reading\nwith open("students.csv", "r") as f:\n    reader = csv.reader(f)\n    next(reader)  # skip header\n    for row in reader:\n        print("Name:", row[1], "Marks:", row[2])\n\n# Search userid/password program\ndef search_password(user_id):\n    with open("users.csv", "r") as f:\n        reader = csv.reader(f)\n        for row in reader:\n            if row[0] == user_id:\n                print("Password found:", row[1])\n                return\n    print("User ID not found!")`,
    keyPoints:['import csv required','newline="" in open() prevents extra blank lines','writerow() writes ONE row, writerows() writes MULTIPLE rows','reader() returns each row as a list of strings','next(reader) skips the header row','CSV is a text file — can be opened in Excel or Notepad'],
    tips:['Always newline="" when writing or you get extra blank rows','Use "a" mode to add data without deleting existing data','CSV values are always strings — use int() or float() to convert','Use next(reader) to skip header before processing data rows'],
    commonMistakes:['Forgetting newline="" — creates extra blank rows in output','Not importing csv module','CSV numbers are strings by default — must convert explicitly','Using "w" when you want to append — loses all existing data!'],
  },
  {
    title:'Stack Data Structure — LIFO Push Pop Implementation',
    subject:'Python', class:'XII', unit:'Unit 1', topic:'Stack using List',
    difficulty:'Intermediate', order:6, isPublished:true,
    content:`## What is a Stack?\nLinear data structure following **LIFO** principle.\n\n**LIFO = Last In, First Out** — last element added is first removed.\n\n## Real Life Examples\n- Stack of plates in cafeteria\n- Browser Back button history\n- Undo (Ctrl+Z) in text editors\n- Function call stack in programs\n\n## Operations\n\n| Operation | Description |\n|-----------|-------------|\n| PUSH | Add element to TOP |\n| POP | Remove and return from TOP |\n| PEEK/TOP | View top element without removing |\n| isEmpty | Returns True if stack has no elements |\n| size | Returns count of elements |\n\n## Python List as Stack\n- PUSH → \`list.append()\`\n- POP → \`list.pop()\`\n- PEEK → \`list[-1]\`\n\n## Overflow and Underflow\n- **Stack Overflow** — pushing to a FULL stack (with size limit)\n- **Stack Underflow** — popping from an EMPTY stack — always check isEmpty() first!`,
    syntax:`class Stack:\n    def __init__(self):\n        self.items = []        # empty list = empty stack\n\n    def push(self, item):\n        self.items.append(item)   # add to top\n\n    def pop(self):\n        if self.is_empty():\n            print("Stack Underflow! Stack is empty.")\n            return None\n        return self.items.pop()   # remove from top, return it\n\n    def peek(self):               # also called top()\n        if self.is_empty():\n            return None\n        return self.items[-1]     # view top without removing\n\n    def is_empty(self):\n        return len(self.items) == 0\n\n    def size(self):\n        return len(self.items)\n\n    def display(self):\n        if self.is_empty():\n            print("Stack is empty")\n        else:\n            print("Stack (top→bottom):", self.items[::-1])\n\n\n# Using the Stack\ns = Stack()\ns.push(10)\ns.push(20)\ns.push(30)\ns.push(40)\ns.display()                  # [40, 30, 20, 10]\nprint("Top:", s.peek())      # 40\nprint("Size:", s.size())     # 4\nprint("Pop:", s.pop())       # 40\nprint("Pop:", s.pop())       # 30\ns.display()                  # [20, 10]\nprint("Empty?", s.is_empty()) # False\n\n# Tracing exam question:\n# Push 5 → [5]\n# Push 3 → [5,3]  (3 on top)\n# Pop    → returns 3, stack=[5]\n# Push 8 → [5,8]  (8 on top)\n# Pop    → returns 8, stack=[5]\n# Pop    → returns 5, stack=[]`,
    keyPoints:['Stack = LIFO — Last In First Out','Python list append() is the PUSH operation','Python list pop() is the POP operation','items[-1] gives the top element (PEEK) without removing','Always check is_empty() before pop to avoid Underflow','Stack used in: recursion, undo operations, expression evaluation'],
    tips:['Draw a stack diagram in exams — trace push/pop step by step','Right end of list = top of stack','Practice tracing push/pop sequences on paper','Always show underflow check in exam answers for full marks'],
    commonMistakes:['Popping from empty stack — always check is_empty() first!','Confusing LIFO (Stack) with FIFO (Queue)','Using insert(0, item) for push — wrong! Use append()','Forgetting to return value in pop() method'],
  },

  // ══════════════════ CLASS XII — NETWORKS ══════════════════
  {
    title:'Computer Networks — Evolution ARPANET NSFNET Internet',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Evolution of Networking',
    difficulty:'Basic', order:10, isPublished:true,
    content:`## What is a Computer Network?\nGroup of computers connected to **share data and resources**.\n\n## Evolution of Networking\n\n### ARPANET (1969)\n- First computer network\n- Created by US Department of Defense (DARPA)\n- Connected 4 universities initially\n- First use of **packet switching**\n- Full form: Advanced Research Projects Agency NETwork\n\n### NSFNET (1986)\n- National Science Foundation NETwork\n- Replaced ARPANET\n- Connected US universities and research centers\n- Speed: 56 Kbps → upgraded to 45 Mbps\n\n### INTERNET (1991 onwards)\n- Global network of networks\n- **Tim Berners-Lee** invented WWW (World Wide Web) in 1991\n- Open to the public\n- Uses TCP/IP protocols\n- Billions of devices connected today\n\n## 5 Components of Data Communication\n1. **Sender** — device that sends data\n2. **Receiver** — device that receives data\n3. **Message** — the data being sent\n4. **Communication Media** — path (cable or wireless)\n5. **Protocols** — rules for communication\n\n## Switching Techniques\n- **Circuit Switching** — dedicated path reserved for entire session (telephone calls)\n- **Packet Switching** — data split into packets, each can take different route (internet)`,
    syntax:`import socket\nhostname = socket.gethostname()\nip = socket.gethostbyname(hostname)\nprint("Hostname:", hostname)\nprint("IP Address:", ip)\n\n# Memory trick — evolution order:\n# ARPANET (1969) → NSFNET (1986) → INTERNET (1991)\n# Defense        → Science       → Public\n\n# Switching comparison:\n# Circuit Switching = dedicated path = telephone\n#   → whole path reserved, wastes if idle\n# Packet Switching  = data in packets = internet\n#   → efficient, packets take different routes`,
    keyPoints:['ARPANET (1969) — first network, US Defense, packet switching','NSFNET (1986) — academic/research, replaced ARPANET','Internet (1991) — public, Tim Berners-Lee invented WWW','5 components: Sender, Receiver, Message, Media, Protocols','Packet Switching = internet, Circuit Switching = telephone','IP address = unique address of every device on network'],
    tips:['Remember order: ARPANET → NSFNET → INTERNET and years 1969, 1986, 1991','Packet switching: data in packets, can take different routes, efficient','Tim Berners-Lee invented WWW, not the internet itself'],
    commonMistakes:['Confusing ARPANET year (1969) with NSFNET (1986)','Saying internet was invented by USA — WWW was by Tim Berners-Lee','Confusing Bandwidth (max capacity) with Speed (actual transfer rate)'],
  },
  {
    title:'Transmission Media — Twisted Pair Coaxial Fiber Wireless',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Transmission Media',
    difficulty:'Basic', order:11, isPublished:true,
    content:`## Types of Transmission Media\n\n## Wired (Guided) Media\n\n### 1. Twisted Pair Cable\n- Two copper wires twisted together\n- **UTP** (Unshielded) — most common, LAN, offices\n- **STP** (Shielded) — has protective metallic shield\n- Speed: 10 Mbps to 1 Gbps | Range: up to 100 metres | Cheapest\n- Used in: LAN (Ethernet), telephone lines\n\n### 2. Coaxial Cable\n- Central copper conductor + insulator + metallic shield + outer cover\n- Speed: up to 10 Gbps | Range: up to 500 metres\n- Used in: Cable TV, older Ethernet networks\n\n### 3. Fiber Optic Cable\n- Uses **light pulses** to transmit data — NOT electricity\n- Fastest | Most expensive | Not affected by electromagnetic interference\n- Speed: up to 100 Gbps\n- Used in: Internet backbone, hospitals, long-distance communication\n\n## Wireless (Unguided) Media\n\n### Radio Waves (3 KHz – 1 GHz)\n- Can pass through walls\n- Used in: WiFi, Bluetooth, AM/FM radio\n\n### Microwaves (1 GHz – 300 GHz)\n- **Line of sight** transmission required\n- Used in: Satellite communication, mobile networks, radar\n\n### Infrared Waves\n- Very short range, line of sight only\n- Cannot pass through walls\n- Used in: TV remotes, wireless keyboard/mouse`,
    syntax:`# Memory trick: TCF for wired\n# T = Twisted pair  → Telephone, LAN, cheapest\n# C = Coaxial        → Cable TV, medium speed\n# F = Fiber Optic    → Fastest, uses LIGHT, most expensive\n\n# Memory trick: RMI for wireless\n# R = Radio     → WiFi, Bluetooth, passes through walls\n# M = Microwave → Line of sight, satellite, towers\n# I = Infrared  → TV remote, very short range, no walls`,
    keyPoints:['Twisted Pair — cheapest — UTP for LAN offices, STP shielded','Coaxial — central copper + metal shield — Cable TV','Fiber Optic — uses LIGHT not electricity — fastest — most expensive','Radio Waves — WiFi and Bluetooth — passes through walls','Microwaves — needs line of sight — satellite and mobile','Infrared — very short range — TV remotes, cannot pass walls'],
    tips:['Fiber = Fastest = Light = Expensive','Twisted pair = cheapest, most common in schools and offices','Infrared requires direct line of sight — that is why TV remote must face TV','Microwave towers on buildings because they need line of sight'],
    commonMistakes:['Saying fiber optic uses electricity — it uses LIGHT pulses','Confusing infrared with radio waves — infrared cannot pass through walls','Forgetting that coaxial cable has copper conductor inside'],
  },
  {
    title:'Network Devices — Hub Switch Router Modem Gateway',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Network Devices',
    difficulty:'Basic', order:12, isPublished:true,
    content:`## Important Network Devices\n\n### Modem (MOdulator DEModulator)\n- Converts digital signal ↔ analog signal\n- Used to connect to internet via telephone line\n\n### NIC / Ethernet Card\n- Network Interface Card — hardware inside computer\n- Has a unique **MAC address**\n- Required for wired network connection\n\n### RJ45 Connector\n- Rectangular plug at end of Ethernet cable\n- Like a wider telephone plug\n\n### Repeater\n- Amplifies weak signal and retransmits\n- Extends network range, 2 ports\n- Just amplifies — no filtering or intelligence\n\n### Hub\n- Connects multiple computers\n- **Broadcasts data to ALL** connected devices (dumb)\n- Being replaced by switches\n\n### Switch\n- Smarter than hub\n- Sends data **only to target device** using MAC address\n- Reduces traffic, much more efficient\n- Used in all modern LANs\n\n### Router\n- Connects **two or more different networks**\n- Finds the **best path** for packets using IP address\n- Every home has a WiFi router\n\n### Gateway\n- Connects networks with **different protocols**\n- Acts as translator between incompatible networks\n\n### WiFi Card\n- Wireless NIC — built into modern laptops`,
    syntax:`# Key comparison to remember:\n\n# Hub vs Switch:\n# Hub    → broadcasts to ALL  → wastes bandwidth → old tech\n# Switch → sends to TARGET    → efficient        → modern\n\n# Switch vs Router:\n# Switch → same network    → uses MAC address\n# Router → diff networks   → uses IP address\n\n# Repeater vs Hub:\n# Repeater → 2 ports, just boosts signal\n# Hub      → many ports, sends to all\n\n# IP vs MAC:\n# MAC = hardware address (permanent, like your name)\n# IP  = software address (can change, like your phone number)`,
    keyPoints:['Modem — digital to analog conversion — internet via phone line','NIC — has unique MAC address — needed for network connection','Hub — broadcasts to ALL — dumb — old technology','Switch — sends to TARGET using MAC address — smart — modern','Router — connects DIFFERENT networks — uses IP address','Gateway — connects different protocol networks — translator'],
    tips:['Hub = dumb (sends everywhere), Switch = smart (sends to target only)','Router = what you have at home for WiFi internet','Every device has MAC (permanent hardware) and IP (changeable software) address'],
    commonMistakes:['Confusing Hub (broadcasts) with Switch (targeted to MAC)','Saying Router uses MAC address — it uses IP address','Confusing Repeater (signal booster only) with Router (network connector)'],
  },
  {
    title:'Network Types LAN WAN MAN PAN — Bus Star Tree Topologies',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Network Topologies',
    difficulty:'Basic', order:13, isPublished:true,
    content:`## Types of Networks by Range\n\n| Type | Full Form | Range | Example |\n|------|-----------|-------|---------|\n| PAN | Personal Area Network | ~10 metres | Bluetooth between phone and laptop |\n| LAN | Local Area Network | up to 1 km | **School computer lab**, office |\n| MAN | Metropolitan Area Network | up to 100 km | City-wide cable TV network |\n| WAN | Wide Area Network | Worldwide | **Internet** is largest WAN |\n\n## Network Topologies\nThe physical or logical **arrangement** of computers in a network.\n\n### Bus Topology\n- All computers connected to a **single backbone cable**\n- Data travels in both directions\n- **Advantages:** Simple, cheap, easy to install\n- **Disadvantages:** If backbone breaks → entire network fails\n\n### Star Topology ⭐ (Most Common Today)\n- All computers connected to a **central hub or switch**\n- **Advantages:** If one PC fails → others still work; easy to add/remove\n- **Disadvantages:** If hub/switch fails → entire network fails; needs more cable\n\n### Tree Topology\n- Hierarchical combination of Bus and Star topologies\n- Used in large organizations with multiple departments\n- **Advantages:** Scalable, easy to manage sections\n- **Disadvantages:** Root node failure = entire section fails`,
    syntax:`# Network type by range:\n# PAN < LAN < MAN < WAN\n# Personal < Local < Metropolitan < Wide\n\n# Best exam examples:\n# School computer lab = LAN\n# Internet = WAN (largest)\n# City WiFi network = MAN\n# Bluetooth headphones = PAN\n\n# Topology failure points:\n# Bus   = backbone cable breaks → ALL computers fail\n# Star  = one PC fails → others fine, hub fails → ALL fail\n# Tree  = root fails → whole section fails`,
    keyPoints:['PAN < LAN < MAN < WAN — ordered by range','Internet is the largest example of WAN','School computer lab = best LAN example for exams','Bus — single cable — cheap but one break = whole network down','Star — central hub/switch — MOST POPULAR — one PC fail is OK','Tree — hierarchical Bus+Star combination — large organizations'],
    tips:['School computer lab = LAN (best example to write in exam)','Star topology is MOST COMMON in real life today','Bus = one break = whole network down = not reliable'],
    commonMistakes:['Saying internet is LAN — internet is WAN (worldwide)','In star topology, saying one PC failure stops network — it does NOT','Confusing MAN (city range) with LAN (building range)'],
  },
  {
    title:'Network Protocols — HTTP FTP SMTP TCP/IP VoIP POP3',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Network Protocols',
    difficulty:'Basic', order:14, isPublished:true,
    content:`## What is a Protocol?\nA set of **rules** that computers must follow to communicate with each other — like grammar rules for language.\n\n## Important Protocols\n\n| Protocol | Full Form | Use |\n|----------|-----------|-----|\n| HTTP | HyperText Transfer Protocol | Loading web pages |\n| HTTPS | HTTP Secure | Secure web (banking, shopping) |\n| FTP | File Transfer Protocol | Upload/download files |\n| SMTP | Simple Mail Transfer Protocol | **Sending** emails |\n| POP3 | Post Office Protocol version 3 | **Receiving/downloading** emails |\n| TCP/IP | Transmission Control Protocol/Internet Protocol | Foundation of all internet |\n| PPP | Point to Point Protocol | Dial-up internet connections |\n| TELNET | TELetype NETwork | Remote login (not secure) |\n| VoIP | Voice over Internet Protocol | WhatsApp calls, Zoom, Google Meet |\n\n## WWW vs Internet\n- **Internet** = the physical network of computers worldwide\n- **WWW** = a service that runs ON the internet (web pages and hyperlinks)\n\n## HTTPS vs HTTP\n- HTTPS = HTTP + SSL (Secure Socket Layer) encryption\n- Shows padlock symbol in browser address bar\n- Used for all secure sites: banking, shopping, login pages`,
    syntax:`# Protocol by use — easy to remember:\n# Browsing websites  → HTTP or HTTPS\n# Downloading files   → FTP\n# Sending email       → SMTP  (S for Send)\n# Receiving email     → POP3  (P for Post Office)\n# All internet data   → TCP/IP (the foundation)\n# Voice calls online  → VoIP  (WhatsApp, Zoom)\n# Remote computer     → TELNET (old, not secure)\n\n# HTTPS = HTTP + SSL encryption\n# SSL = Secure Sockets Layer\n# Padlock shown in browser = HTTPS\n\n# Python example — using HTTP:\nimport urllib.request\n# response = urllib.request.urlopen("https://cbse.gov.in")`,
    keyPoints:['HTTP — web pages. HTTPS — secure web with SSL encryption','FTP — file transfer between computers over network','SMTP — Sending email. POP3 — Receiving and downloading email','TCP/IP — foundation of all internet communication','VoIP — voice calls over internet — WhatsApp, Zoom, Google Meet','TELNET — remote login — insecure, replaced by SSH'],
    tips:['SMTP = Simple Mail Transfer = Sending (S for Send)','POP3 = Post Office Protocol = collect/download mail','HTTPS = HTTP + SSL = padlock shown in browser address bar','VoIP = Voice over IP = internet calling technology'],
    commonMistakes:['Confusing SMTP (send mail) with POP3 (receive mail)','Saying HTTP and HTTPS are completely different — HTTPS is just HTTP with SSL','Confusing Internet (physical network) with WWW (service on internet)'],
  },
  {
    title:'Web Services — WWW HTML URL Domain Web Hosting Browser',
    subject:'Networks', class:'XII', unit:'Unit 2: Computer Networks', topic:'Web Services',
    difficulty:'Basic', order:15, isPublished:true,
    content:`## World Wide Web (WWW)\n- Created by **Tim Berners-Lee** in 1991 at CERN, Switzerland\n- Collection of web pages connected by hyperlinks\n- Web pages written in HTML\n- Accessed using a web browser\n\n## Key Terms\n\n### HTML — HyperText Markup Language\n- Language used to create web pages\n- Uses tags: \`<html>\`, \`<body>\`, \`<h1>\`, \`<p>\`, \`<a href>\`\n- Describes structure and content of web page\n\n### XML — eXtensible Markup Language\n- Stores and transports data\n- Tags are user-defined (not fixed like HTML)\n- Used in web services and data exchange\n\n### URL — Uniform Resource Locator\nComplete address of a web page.\nStructure: \`protocol://domain-name/path\`\nExample: \`https://www.cbse.gov.in/results/index.html\`\n\n### Domain Name Extensions\n- **.com** → commercial organizations\n- **.edu** → educational institutions\n- **.gov** → government\n- **.in** → India country code\n- **.org** → non-profit organizations\n\n### Web Browser\nSoftware to access and display web pages.\nExamples: Google Chrome, Firefox, Microsoft Edge, Safari\n\n### Web Server\nComputer that stores web pages and sends them when requested.\n\n### Web Hosting\nRenting space on a web server to publish your website online.`,
    syntax:`# URL structure breakdown:\nurl = "https://www.cbse.gov.in/results/index.html"\n# Protocol    = https\n# Sub-domain  = www\n# Domain      = cbse.gov.in\n# Extension   = .in (India) + .gov (government)\n# Path        = /results/index.html\n\n# Basic HTML web page structure:\n"""\n<!DOCTYPE html>\n<html>\n  <head>\n    <title>Chinmaya Vidyalaya NTPC Unchahar</title>\n  </head>\n  <body>\n    <h1>Welcome Students!</h1>\n    <p>Class X and XII Computer Science Portal</p>\n    <a href="https://cbse.gov.in">Visit CBSE Website</a>\n  </body>\n</html>\n"""`,
    keyPoints:['WWW created by Tim Berners-Lee in 1991 at CERN','HTML creates web pages; XML stores/transports data','URL = complete address: protocol + domain + path','Domain extensions: .com .edu .gov .in .org','Web hosting = renting server space to publish website','HTTPS = HTTP + SSL = secure, shows padlock in browser'],
    tips:['URL has 3 main parts: protocol + domain + path','WWW is a service ON the internet — not the internet itself','Tim Berners-Lee invented WWW, not the internet'],
    commonMistakes:['Saying WWW and internet are same thing — they are different','Confusing HTML (creates web pages) with HTTP (transfers web pages)','Forgetting domain extension meanings in exam'],
  },

  // ══════════════════ CLASS XII — DATABASE ══════════════════
  {
    title:'Database Concepts — Relation Attribute Tuple Keys',
    subject:'Database', class:'XII', unit:'Unit 3: Database Management', topic:'Database Concepts & Keys',
    difficulty:'Basic', order:20, isPublished:true,
    content:`## What is a Database?\nOrganized collection of related data. Easy to access, manage, and update.\n\n## DBMS — Database Management System\nSoftware that manages databases.\nExamples: MySQL, Oracle, MS Access, SQLite\n\n## Relational Data Model — Important Terms\n\n| Term | Meaning | Example |\n|------|---------|--------|\n| **Relation / Table** | A table with rows and columns | Students table |\n| **Attribute** | A column (a property/field) | name, rollno, marks |\n| **Tuple** | A row (one complete record) | (1, Rahul, 85) |\n| **Domain** | Allowed set of values for attribute | marks: 0 to 100 |\n| **Degree** | Number of **columns** in table | 4 columns → degree = 4 |\n| **Cardinality** | Number of **rows** in table | 30 rows → cardinality = 30 |\n\n## Types of Keys\n\n### Candidate Key\n- Attribute(s) that can uniquely identify each row\n- A table can have multiple candidate keys\n- Minimal — no extra attributes needed\n\n### Primary Key\n- The chosen candidate key for a table\n- **Cannot be NULL**\n- Only **ONE** primary key per table\n- Uniquely identifies every row\n\n### Alternate Key\n- Candidate keys that were NOT chosen as primary key\n\n### Foreign Key\n- Attribute in one table that refers to **Primary Key** of another table\n- Creates relationship between two tables\n- Can have duplicate values and can be NULL`,
    syntax:`-- Example Table: students\n-- rollno | name          | marks | city\n-- -------|---------------|-------|----------\n-- 1      | Rahul Sharma  | 85    | Unchahar\n-- 2      | Priya Singh   | 92    | Raebareli\n-- 3      | Amit Kumar    | 78    | Lucknow\n\n-- rollno = PRIMARY KEY (unique, not null)\n-- Degree = 4 (4 columns: rollno, name, marks, city)\n-- Cardinality = 3 (3 rows/tuples)\n\n-- Foreign Key example:\n-- marks table: (rollno, subject, score)\n-- rollno here is FOREIGN KEY → refers to students.rollno\n\n-- In Python as dictionary:\nstudents = [\n    {"rollno": 1, "name": "Rahul", "marks": 85},\n    {"rollno": 2, "name": "Priya", "marks": 92},\n]\n# rollno acts as Primary Key — unique for each student`,
    keyPoints:['Relation=Table, Attribute=Column, Tuple=Row','Degree = number of columns in table','Cardinality = number of rows in table','Primary Key — uniquely identifies each row — cannot be NULL — only ONE per table','Candidate Key — all attributes that could be primary key','Foreign Key — references Primary Key of another table — creates relationship'],
    tips:['Degree = columns (think "degree of columns"), Cardinality = rows','Primary Key never has duplicates and never NULL','Foreign Key can have duplicates and can be NULL','Rollno is always the best example of Primary Key in school context'],
    commonMistakes:['Confusing Degree (columns) with Cardinality (rows)','Saying Primary Key can have NULL values — it absolutely cannot','A table can have only ONE primary key','Forgetting the difference between Candidate Key and Primary Key'],
  },
  {
    title:'SQL — Complete Commands with Examples',
    subject:'Database', class:'XII', unit:'Unit 3: Database Management', topic:'SQL Commands',
    difficulty:'Intermediate', order:21, isPublished:true,
    content:`## SQL — Structured Query Language\nLanguage used to communicate with relational databases.\n\n## DDL — Data Definition Language (structure)\n- **CREATE** — create database or table\n- **ALTER** — modify table structure\n- **DROP** — delete table or database\n\n## DML — Data Manipulation Language (data)\n- **INSERT** — add new rows\n- **SELECT** — retrieve data\n- **UPDATE** — modify existing data\n- **DELETE** — remove rows\n\n## SQL Data Types\n| Type | Use |\n|------|-----|\n| CHAR(n) | Fixed length text |\n| VARCHAR(n) | Variable length text |\n| INT | Whole numbers |\n| FLOAT | Decimal numbers |\n| DATE | Date values |\n\n## Constraints\n- **NOT NULL** — column cannot be empty\n- **UNIQUE** — all values must be different\n- **PRIMARY KEY** — NOT NULL + UNIQUE combined\n\n## Important Clauses\n- **WHERE** — filter rows before grouping\n- **ORDER BY** — sort (ASC = ascending default, DESC = descending)\n- **DISTINCT** — remove duplicate values from result\n- **LIKE** — pattern match (% = any chars, _ = exactly one char)\n- **IN** — match from a list\n- **BETWEEN** — range, both ends inclusive\n- **IS NULL / IS NOT NULL** — check null values\n- **GROUP BY** — group rows for aggregate functions\n- **HAVING** — filter groups (like WHERE but after GROUP BY)\n\n## Aggregate Functions\n**COUNT()**, **SUM()**, **AVG()**, **MAX()**, **MIN()**\n\n## Joins\n- **Cartesian Product** — every row of table1 × every row of table2\n- **Equi-Join** — join using equality condition\n- **Natural Join** — auto-join on common column name`,
    syntax:`-- CREATE database and table\nCREATE DATABASE school;\nUSE school;\n\nCREATE TABLE students (\n    rollno INT PRIMARY KEY,\n    name   VARCHAR(50) NOT NULL,\n    class  VARCHAR(5),\n    marks  INT,\n    city   VARCHAR(30)\n);\n\n-- INSERT rows\nINSERT INTO students VALUES (1,'Rahul Sharma','XII',85,'Unchahar');\nINSERT INTO students VALUES (2,'Priya Singh','XII',92,'Raebareli');\nINSERT INTO students VALUES (3,'Amit Kumar','X',78,'Unchahar');\nINSERT INTO students VALUES (4,'Sneha Gupta','X',88,'Lucknow');\nINSERT INTO students VALUES (5,'Rohit Verma','XII',65,'Allahabad');\n\n-- SELECT basics\nSELECT * FROM students;\nSELECT name, marks FROM students WHERE marks > 80;\nSELECT * FROM students ORDER BY marks DESC;\nSELECT DISTINCT city FROM students;\n\n-- LIKE patterns\nSELECT * FROM students WHERE name LIKE 'R%';   -- starts with R\nSELECT * FROM students WHERE name LIKE '%ma';  -- ends with ma\nSELECT * FROM students WHERE name LIKE '_a%';  -- 2nd char = a\n\n-- IN and BETWEEN\nSELECT * FROM students WHERE city IN ('Unchahar','Lucknow');\nSELECT * FROM students WHERE marks BETWEEN 70 AND 90;\n\n-- IS NULL\nSELECT * FROM students WHERE city IS NULL;\n\n-- Aggregate functions\nSELECT COUNT(*) FROM students;\nSELECT AVG(marks), MAX(marks), MIN(marks), SUM(marks) FROM students;\n\n-- GROUP BY with HAVING\nSELECT class, COUNT(*) AS total, AVG(marks) AS average\nFROM students\nGROUP BY class\nHAVING AVG(marks) > 80;\n\n-- UPDATE (ALWAYS use WHERE!)\nUPDATE students SET marks = 95 WHERE rollno = 2;\n\n-- DELETE (ALWAYS use WHERE!)\nDELETE FROM students WHERE rollno = 5;\n\n-- ALTER TABLE\nALTER TABLE students ADD COLUMN phone VARCHAR(15);\nALTER TABLE students DROP COLUMN phone;\nALTER TABLE students MODIFY marks FLOAT;\n\n-- DROP\nDROP TABLE students;\nDROP DATABASE school;\n\n-- JOINS\n-- Equi-Join:\nSELECT students.name, subjects.subject, subjects.score\nFROM students, subjects\nWHERE students.rollno = subjects.rollno;\n\n-- Natural Join:\nSELECT * FROM students NATURAL JOIN subjects;`,
    keyPoints:['DDL: CREATE ALTER DROP — change structure','DML: INSERT SELECT UPDATE DELETE — work with data','WHERE filters rows, HAVING filters groups after GROUP BY','ORDER BY ASC (default) or DESC','LIKE: % = any chars, _ = exactly one char','ALWAYS use WHERE with UPDATE and DELETE or ALL rows are affected!','Aggregate functions: COUNT SUM AVG MAX MIN'],
    tips:['WHERE vs HAVING: WHERE is before GROUP BY, HAVING is after GROUP BY','BETWEEN is inclusive — BETWEEN 70 AND 90 includes both 70 and 90','ALWAYS WHERE with UPDATE/DELETE — without it modifies ALL rows!','SELECT DISTINCT removes duplicate rows from result set'],
    commonMistakes:['Using HAVING without GROUP BY','Forgetting WHERE in UPDATE or DELETE — all rows get changed!','Using = NULL instead of IS NULL — SQL always uses IS NULL','Confusing CHAR (fixed size) with VARCHAR (variable size)'],
  },
  {
    title:'Python MySQL Connectivity — cursor execute fetchall commit',
    subject:'Database', class:'XII', unit:'Unit 3: Database Management', topic:'Python SQL Connectivity',
    difficulty:'Advanced', order:22, isPublished:true,
    content:`## Connecting Python with MySQL\nPython connects to MySQL using \`mysql-connector-python\` library.\n\n## 7 Steps of Database Connectivity\n1. **Import** mysql.connector module\n2. **connect()** — create connection to MySQL server\n3. **cursor()** — create cursor object\n4. **execute()** — run SQL query\n5. **fetchone() / fetchall()** — get results\n6. **commit()** — save changes permanently\n7. **close()** — close cursor and connection\n\n## Key Functions\n\n| Function | Use |\n|----------|-----|\n| connect() | Create connection to MySQL |\n| cursor() | Create cursor to execute queries |\n| execute(query) | Run a SQL query |\n| fetchone() | Get ONE row from result |\n| fetchall() | Get ALL rows as list of tuples |\n| rowcount | Number of rows affected |\n| commit() | Save INSERT/UPDATE/DELETE changes |\n| close() | Close connection or cursor |\n\n## %s Format Specifier\nUse %s as placeholder — safer than putting values directly in query.\nPrevents SQL injection attacks.\nAlways pass values as a **tuple**: \`(value,)\` — note the comma for single value!`,
    syntax:`import mysql.connector\n\n# Step 1 & 2: Import and Connect\nconn = mysql.connector.connect(\n    host="localhost",\n    user="root",\n    password="your_password",\n    database="school"\n)\n\n# Step 3: Create cursor\ncursor = conn.cursor()\n\n# SELECT — fetchall()\ncursor.execute("SELECT * FROM students")\nrows = cursor.fetchall()\nfor row in rows:\n    print(row)  # each row is a tuple: (1, 'Rahul', 85, 'Unchahar')\n\n# SELECT — fetchone() one row at a time\ncursor.execute("SELECT * FROM students")\nrow = cursor.fetchone()   # first row\nprint(row)\nrow = cursor.fetchone()   # second row\nprint(row)\n\n# SELECT with %s (safe parameterized query)\nrollno = int(input("Enter roll number: "))\ncursor.execute(\n    "SELECT name, marks FROM students WHERE rollno = %s",\n    (rollno,)  # tuple — note the comma after rollno!\n)\nresult = cursor.fetchone()\nif result:\n    print("Name:", result[0], "Marks:", result[1])\nelse:\n    print("Student not found")\n\n# INSERT with %s\nname  = input("Name: ")\nmarks = int(input("Marks: "))\ncursor.execute(\n    "INSERT INTO students (name, marks) VALUES (%s, %s)",\n    (name, marks)\n)\nconn.commit()  # MUST commit after INSERT!\nprint("Rows inserted:", cursor.rowcount)\n\n# UPDATE with %s\nnew_marks = int(input("New marks: "))\nroll = int(input("Roll no: "))\ncursor.execute(\n    "UPDATE students SET marks = %s WHERE rollno = %s",\n    (new_marks, roll)\n)\nconn.commit()  # MUST commit after UPDATE!\nprint("Rows updated:", cursor.rowcount)\n\n# DELETE with %s\nroll = int(input("Roll to delete: "))\ncursor.execute(\n    "DELETE FROM students WHERE rollno = %s",\n    (roll,)\n)\nconn.commit()  # MUST commit after DELETE!\nprint("Rows deleted:", cursor.rowcount)\n\n# Step 7: Close\ncursor.close()\nconn.close()`,
    keyPoints:['import mysql.connector is the first step','connect() needs: host, user, password, database','cursor() creates object to execute SQL queries','execute() runs the SQL query string','fetchone() returns one row, fetchall() returns all rows as list of tuples','commit() is MANDATORY after INSERT, UPDATE, DELETE — or changes are lost!','%s placeholder for safe parameterized queries — always pass as tuple'],
    tips:['Always commit() after modifying data or changes will be lost','fetchall() returns list of tuples — each tuple is one row','Always close() cursor and connection when finished','Pass values as tuple even for one value: (id,) not just (id)'],
    commonMistakes:['Forgetting commit() after INSERT/UPDATE/DELETE — changes not saved!','Not passing values as tuple in execute() — causes error','Forgetting import mysql.connector','Connecting to wrong database name in connect()'],
  },

  // ══════════════════ CLASS X — AI SYLLABUS ══════════════════
  {
    title:'AI Project Cycle — 5 Stages Complete Guide',
    subject:'AI', class:'X', unit:'Unit 1: AI Foundations', topic:'AI Project Cycle',
    difficulty:'Basic', order:30, isPublished:true,
    content:`## What is the AI Project Cycle?\nA systematic **5-stage process** followed to build any AI project successfully.\n\n## The 5 Stages\n\n### Stage 1: Problem Scoping 🎯\n- Define the problem clearly before anything else\n- Identify who is affected and what is the goal\n- Ask: **What problem are we solving?**\n- This is the MOST IMPORTANT stage\n\n### Stage 2: Data Acquisition 📦\n- Collect relevant data for the problem\n- Data types: images, text, numbers, audio, video\n- More good quality data = better AI model\n- Ask: **What data do we need and where to get it?**\n\n### Stage 3: Data Exploration 🔍\n- Understand the collected data\n- Find patterns, outliers, missing values\n- Visualise data using charts and graphs\n- Ask: **What patterns does the data show?**\n\n### Stage 4: Modelling 🤖\n- Choose the appropriate ML algorithm\n- Train the model on collected data\n- Model learns patterns from data\n- Ask: **Which model fits the problem best?**\n\n### Stage 5: Evaluation ✅\n- Test model with NEW, unseen data\n- Measure accuracy and performance\n- If not good enough → go back and improve data or model\n- Ask: **How accurate and reliable is our model?**\n\n## Three Domains of AI\n1. **Computer Vision** — AI that sees and understands images\n2. **Natural Language Processing (NLP)** — AI that understands text and speech\n3. **Data Science** — AI that finds patterns in numerical data`,
    syntax:`# Remember the 5 stages: P-D-E-M-E\n# Problem Scoping\n# Data Acquisition\n# Data Exploration\n# Modelling\n# Evaluation\n\n# Real example — Plant Disease Detection:\n# Stage 1 (Problem)  : Identify healthy vs diseased leaf\n# Stage 2 (Data)     : Collect 10,000 leaf photos\n# Stage 3 (Explore)  : Check image quality, balance classes\n# Stage 4 (Model)    : Train CNN on leaf photos\n# Stage 5 (Evaluate) : Test on new photos, check accuracy %\n\n# If evaluation is bad → go back to Stage 2 (more data)\n# or Stage 4 (try different model)\n\n# Three AI Domains:\n# Computer Vision → face recognition, self-driving, medical scans\n# NLP             → Google Translate, Alexa, spam filter, chatbots\n# Data Science    → stock prediction, recommendation, fraud detection`,
    keyPoints:['5 stages: Problem Scoping → Data Acquisition → Data Exploration → Modelling → Evaluation','Problem Scoping first — wrong problem = completely wasted effort','Data Acquisition: quality of data matters more than quantity','Data Exploration: understand, visualize, and clean the data','Modelling: choose algorithm and train model on data','Evaluation: test with NEW data, improve if needed','Three domains: Computer Vision, NLP, Data Science'],
    tips:['Remember P-D-E-M-E in order','If evaluation is bad, go back to data collection or modelling','Never skip data exploration — it reveals data quality issues','Problem scoping is the most critical stage of all'],
    commonMistakes:['Starting with modelling before proper data collection','Skipping data exploration — leads to poor model','Not going back to improve when evaluation score is poor','Confusing Data Acquisition (collecting) with Data Exploration (analyzing)'],
  },
  {
    title:'AI vs ML vs DL — Differences and Relationship',
    subject:'AI', class:'X', unit:'Unit 1', topic:'AI ML DL Differences',
    difficulty:'Basic', order:31, isPublished:true,
    content:`## The Relationship Between AI, ML, and DL\n\nAI ⊃ ML ⊃ DL\n\n- **AI** is the broadest concept (outer circle)\n- **ML** is a subset of AI (middle circle)\n- **DL** is a subset of ML (inner circle)\n\n## Artificial Intelligence (AI)\n- Making computers perform tasks that need human intelligence\n- Can be **rule-based** (no learning) or **learning-based** (learns from data)\n- Examples: chess engine, face unlock, Google Maps routing, recommendation systems\n\n## Machine Learning (ML)\n- Type of AI where computer **learns from data** without being explicitly programmed\n- Algorithm finds patterns in training data and improves over time\n- No need to write rules manually — model learns them\n- Examples: spam filter, Netflix recommendations, price prediction, fraud detection\n\n## Deep Learning (DL)\n- Type of ML that uses **Artificial Neural Networks** with many layers\n- Inspired by the human brain structure\n- Works best with large amounts of data (images, audio, video, text)\n- Automatically extracts features from raw data\n- Examples: Voice assistants (Siri, Alexa), self-driving cars, face recognition\n\n## Key Terms\n| Term | Meaning |\n|------|---------|\n| Training Data | Data used to teach the model |\n| Testing Data | New data used to check model performance |\n| Label | The correct answer in training data |\n| Feature | An input variable used for prediction |\n| Model | The learned set of patterns/rules |`,
    syntax:`# Analogy to understand AI-ML-DL:\n# AI = Teaching a child to identify animals\n# ML = Child learns by seeing thousands of examples\n# DL = Child's brain builds layers of understanding:\n#      Layer 1: detects edges and colors\n#      Layer 2: recognizes shapes\n#      Layer 3: identifies features (ears, tail, fur)\n#      Layer 4: classifies the animal\n\n# Rule-based AI (old approach):\ndef is_spam(email):\n    if "free money" in email or "click here" in email:\n        return True\n    return False\n# Problem: you must manually write ALL rules\n\n# Machine Learning approach:\n# Model trained on 50,000 spam/non-spam examples\n# Learns patterns automatically — no rules needed!\n\n# Deep Learning approach:\n# Neural network processes raw email text\n# Extracts features automatically through layers\n# Much more powerful for complex language patterns\n\n# Draw in exams: Three nested circles\n# Outer = AI, Middle = ML, Inner = DL`,
    keyPoints:['AI > ML > DL — DL is inside ML, ML is inside AI','AI: making machines smart (rule-based OR learning-based)','ML: AI that learns patterns from data automatically','DL: ML using neural networks with multiple layers','Rule-based AI: manually written rules, no learning involved','DL needs more data than ML but handles much more complex tasks'],
    tips:['Always draw three nested circles in exam to show relationship','Simple tasks use ML, complex tasks (images, speech) use DL','DL is inspired by human brain neuron connections','More hidden layers in DL = can learn more complex patterns'],
    commonMistakes:['Saying ML and AI are the same thing — ML is a subset of AI','Saying DL is separate from ML — DL is a type of ML','Confusing features (inputs to model) with labels (correct answers/outputs)'],
  },
  {
    title:'Types of Machine Learning — Supervised Unsupervised Reinforcement',
    subject:'AI', class:'X', unit:'Unit 2', topic:'Types of ML Models',
    difficulty:'Intermediate', order:32, isPublished:true,
    content:`## 1. Supervised Learning\nTrained on **labeled data** — data where correct answers are already provided.\nLike a student studying with answer key.\n\n### Classification (output = category)\n- Examples: Email spam/not spam, image is cat/dog, student pass/fail\n- Tools to try: Teachable Machine (teachablemachine.withgoogle.com)\n\n### Regression (output = number)\n- Examples: Predict house price, predict marks, predict temperature\n\n## 2. Unsupervised Learning\nTrained on **unlabeled data** — no correct answers given.\nModel finds hidden patterns completely on its own.\n\n### Clustering (groups similar items)\n- Examples: Group customers by buying habits, group similar news articles\n\n### Association (finds "bought together" relationships)\n- Examples: "People who buy bread also buy butter" — Amazon, Flipkart recommendations\n\n## 3. Reinforcement Learning\nLearns by **trial and error** with rewards and penalties.\nLike training a pet — reward for correct action, penalty for wrong action.\n- Agent takes actions in environment\n- Gets reward (good) or penalty (bad)\n- Learns to maximize rewards over time\n- Examples: AI playing chess, self-driving car learning to drive\n\n## Comparison\n| Feature | Supervised | Unsupervised | Reinforcement |\n|---------|-----------|--------------|---------------|\n| Data | Labeled | Unlabeled | No fixed data |\n| Output | Prediction | Groups/Patterns | Actions |\n| Example | Spam filter | Customer groups | Game AI |`,
    syntax:`# Supervised — Classification example:\n# Input features: marks, attendance\n# Label (answer): Pass or Fail\ntraining = [\n    {"marks": 85, "attend": 90, "result": "Pass"},\n    {"marks": 35, "attend": 40, "result": "Fail"},\n]\n# Model learns: high marks + attendance → Pass\n\n# Supervised — Regression example:\n# Input: study_hours\n# Output: expected_marks (a NUMBER, not category)\n\n# Unsupervised — Clustering:\n# No labels given — model finds groups automatically\nstudents = [\n    {"marks": 90, "distance": 5},\n    {"marks": 88, "distance": 4},   # similar → cluster A\n    {"marks": 45, "distance": 40},\n    {"marks": 42, "distance": 38},  # similar → cluster B\n]\n\n# Reinforcement — Chess AI:\n# Action: move chess piece\n# Reward: +1 for winning, -1 for losing, 0 for draw\n# After millions of games: learns best moves\n\n# Tools to try:\n# Teachable Machine: teachablemachine.withgoogle.com\n# Drum Machine: experiments.withgoogle.com/ai/drum-machine`,
    keyPoints:['Supervised: labeled data → predict correct output','Classification: output = category (spam, pass/fail, cat/dog)','Regression: output = a number (price, marks, temperature)','Unsupervised: unlabeled data → finds hidden patterns on its own','Clustering: automatically groups similar data points together','Reinforcement: trial-and-error with rewards — game AI, robots'],
    tips:['Supervised = teacher gives correct answers (labeled data)','Unsupervised = no answers given — model discovers groups','Classification = categories, Regression = numbers','Reinforcement = like training a dog — reward and punishment'],
    commonMistakes:['Confusing Regression (predicts numbers) with Classification (predicts categories)','Saying Unsupervised Learning has labeled data — it does NOT','Confusing Clustering (automatic grouping) with Classification (predicting group)'],
  },
  {
    title:'Neural Networks — ANN Structure and How AI Makes Decisions',
    subject:'AI', class:'X', unit:'Unit 2: Neural Networks', topic:'Artificial Neural Networks',
    difficulty:'Intermediate', order:33, isPublished:true,
    content:`## What is a Neural Network?\nA computing system **inspired by the human brain**.\nMade of artificial neurons connected in layers.\n\n## Human Brain vs ANN\n| Human Brain | Artificial Neural Network |\n|-------------|---------------------------|\n| Neurons | Artificial neurons (nodes) |\n| Synapses | Weights (connection strength) |\n| Learning from experience | Training on data |\n| Brain layers/regions | Network layers |\n\n## Structure of a Neural Network\n\n### Input Layer\n- Receives raw data\n- One neuron per input feature\n- For an image: each pixel = one input neuron\n\n### Hidden Layer(s)\n- Processes data and extracts patterns\n- Can have one or many hidden layers\n- More hidden layers = Deep Learning\n\n### Output Layer\n- Gives the final prediction\n- One neuron per output class\n- Example: Cat/Dog classifier → 2 output neurons\n\n## How a Single Neuron Works\n1. Receives inputs (numbers)\n2. Multiplies each input by its **weight** (importance)\n3. Adds a **bias** value\n4. Passes through **activation function**\n5. Outputs a single number\n\n## How AI Makes a Decision\n1. Data enters input layer\n2. Flows through hidden layers extracting features\n3. Output layer gives final prediction\n4. Error calculated and sent backward (**Backpropagation**)\n5. Weights adjusted to reduce error\n6. Repeated thousands of times — model improves!\n\n## Weights\n- Numbers representing strength of connections\n- High weight = important connection\n- **Learned automatically during training**`,
    syntax:`# Single neuron calculation concept:\ndef neuron(inputs, weights, bias):\n    # Step 1: weighted sum\n    total = sum(i * w for i, w in zip(inputs, weights)) + bias\n    # Step 2: activation function (ReLU)\n    return max(0, total)  # if negative → output 0\n\n# Is student likely to pass? (simple example)\ninputs  = [75, 85, 6]      # marks, attendance, study_hours\nweights = [0.4, 0.3, 0.3]  # marks most important (0.4 weight)\nbias = -0.5\n\noutput = neuron(inputs, weights, bias)\nprint("Pass likelihood:", output)\n# output > 0 = likely to pass\n\n# Layer structure concept:\n# Input Layer:  3 neurons (marks, attendance, study_hours)\n# Hidden Layer: 5 neurons (learns hidden patterns)\n# Output Layer: 1 neuron  (pass=1 or fail=0)\n\n# Try TensorFlow Playground — SEE it live!\n# https://playground.tensorflow.org\n# Change layers, neurons, and watch training happen!`,
    keyPoints:['Three layers: Input → Hidden(s) → Output','Each neuron: inputs × weights + bias → activation function','Weights represent importance — learned automatically during training','Backpropagation: error flows backward to update weights','More hidden layers = Deep Learning — handles more complex tasks','Training = repeatedly adjusting weights until predictions are accurate'],
    tips:['Try playground.tensorflow.org — see neural network learn in real time!','More neurons and layers = more powerful but needs more data and time','Activation function decides if neuron "activates" or not','Training = model adjusting its own weights to reduce errors'],
    commonMistakes:['Confusing layers with neurons — layers are groups, neurons are individual units','Saying neural network IS the human brain — it is only INSPIRED by it','Forgetting that weights are automatically learned during training process'],
  },
  {
    title:'Model Evaluation — Accuracy Precision Recall F1 Confusion Matrix',
    subject:'AI', class:'X', unit:'Unit 3: Model Evaluation', topic:'Evaluation Metrics',
    difficulty:'Intermediate', order:34, isPublished:true,
    content:`## Why Evaluate a Model?\nBuilding a model is not enough — we must check how well it performs on **new, unseen data** before using it in real life.\n\n## Confusion Matrix\nFor classification models — shows 4 types of outcomes:\n\n|  | Predicted YES | Predicted NO |\n|--|---------------|--------------|\n| **Actual: YES** | TP (True Positive) ✅ | FN (False Negative) ❌ |\n| **Actual: NO**  | FP (False Positive) ❌ | TN (True Negative) ✅ |\n\n- **TP** = Predicted YES, Actually YES → Correct! ✅\n- **TN** = Predicted NO, Actually NO → Correct! ✅\n- **FP** = Predicted YES, Actually NO → False Alarm! ❌\n- **FN** = Predicted NO, Actually YES → Missed! ❌\n\n## Evaluation Formulas\n\n**Accuracy** = (TP + TN) / (TP + TN + FP + FN) × 100\n→ Overall correct predictions percentage\n\n**Precision** = TP / (TP + FP)\n→ Of all predicted YES, how many were actually YES?\n→ Use when **False Positives** are very costly (e.g., spam filter)\n\n**Recall** = TP / (TP + FN)\n→ Of all actual YES, how many did model correctly find?\n→ Use when **False Negatives** are very costly (e.g., disease detection)\n\n**F1 Score** = 2 × (Precision × Recall) / (Precision + Recall)\n→ Balance between Precision and Recall — use when both matter\n\n## Bias in AI\n- Model performs differently for different groups of people\n- Caused by biased or unrepresentative training data\n- Solution: Use diverse and balanced training data`,
    syntax:`# Example: Medical COVID test for 100 patients\nTP = 40   # Had COVID, correctly detected as positive\nTN = 50   # No COVID, correctly said negative\nFP = 5    # No COVID, but wrongly said positive (false alarm)\nFN = 5    # Had COVID, but wrongly said negative (missed!)\ntotal = TP + TN + FP + FN  # 100\n\n# Calculate metrics\naccuracy  = (TP + TN) / total * 100\nprecision = TP / (TP + FP)\nrecall    = TP / (TP + FN)\nf1 = 2 * (precision * recall) / (precision + recall)\n\nprint(f"Accuracy:  {accuracy}%")      # 90.0%\nprint(f"Precision: {precision:.2f}")  # 0.89\nprint(f"Recall:    {recall:.2f}")     # 0.89\nprint(f"F1 Score:  {f1:.2f}")         # 0.89\n\n# When to use which metric:\n# Spam filter      → high Precision (don't want real email in spam)\n# Cancer detection → high Recall    (never miss a sick patient!)\n# General balanced → F1 Score       (balance of both)\n# Quick overview   → Accuracy`,
    keyPoints:['Confusion Matrix: TP (correct yes), TN (correct no), FP (false alarm), FN (missed)','Accuracy = (TP+TN)/Total — overall correct predictions percentage','Precision = TP/(TP+FP) — of predicted positive, how many correct','Recall = TP/(TP+FN) — of actual positive, how many found by model','F1 = harmonic mean of Precision and Recall — balance between them','Bias = AI treats different groups unfairly due to biased training data'],
    tips:['Disease detection → Recall most important (never miss sick patient)','Spam filter → Precision most important (never miss real emails)','When both matter equally → use F1 Score to balance them','High accuracy can be misleading when data is imbalanced'],
    commonMistakes:['Confusing FP (predicted yes but wrong) with FN (predicted no but wrong)','Using accuracy alone — misleading for imbalanced class data','Mixing up Precision and Recall formulas in exam'],
  },
  {
    title:'Computer Vision — Pixels RGB Grayscale Applications',
    subject:'AI', class:'X', unit:'Unit 4: Computer Vision', topic:'Computer Vision Basics',
    difficulty:'Intermediate', order:35, isPublished:true,
    content:`## What is Computer Vision?\nThe field of AI that enables computers to **see, understand, and interpret** visual information — images and videos.\n\n## Real-World Applications\n- Face recognition (phone unlock, attendance systems)\n- Medical imaging (detecting tumours in X-rays and MRI scans)\n- Self-driving cars (detecting roads, traffic signs, pedestrians)\n- Google Lens (identifying real-world objects from photos)\n- Factory quality control (finding defective products on assembly line)\n- CCTV surveillance and security analysis\n\n## Basics of Digital Images\n\n### Pixel\n- Smallest single unit of a digital image\n- An image is made of thousands or millions of pixels arranged in a grid\n\n### Resolution\n- Total number of pixels = Width × Height\n- 1920 × 1080 = Full HD = 2,073,600 pixels total\n- Higher resolution → clearer image → more data to process\n\n### Grayscale Image\n- Each pixel has exactly **ONE** value: 0 to 255\n- 0 = pure Black, 255 = pure White, 128 = Gray\n- Simpler to process (1 channel only)\n\n### RGB Image\n- Each pixel has exactly **THREE** values: Red, Green, Blue (each 0 to 255)\n- Red = (255, 0, 0) | Green = (0, 255, 0) | Blue = (0, 0, 255)\n- White = (255, 255, 255) | Black = (0, 0, 0) | Yellow = (255, 255, 0)\n\n## Computer Vision Tasks\n1. **Image Classification** — What object is in this image?\n2. **Object Detection** — Where exactly is the object?\n3. **Image Segmentation** — Which pixels belong to which object?\n4. **Feature Extraction** — What unique characteristics exist?`,
    syntax:`# A tiny 3×3 grayscale image as numbers:\nimage_gray = [\n    [0,   128, 255],   # row 1: black, gray, white\n    [64,  100, 200],   # row 2\n    [150,  50,  10],   # row 3\n]\n\n# RGB pixel values:\npixel_red    = (255,   0,   0)  # pure red\npixel_green  = (  0, 255,   0)  # pure green\npixel_blue   = (  0,   0, 255)  # pure blue\npixel_white  = (255, 255, 255)  # white\npixel_black  = (  0,   0,   0)  # black\npixel_yellow = (255, 255,   0)  # red + green = yellow\n\n# Calculate image data size:\nwidth, height = 1920, 1080\ntotal_pixels  = width * height       # 2,073,600 pixels\nrgb_values    = total_pixels * 3     # 6,220,800 values (3 per pixel)\n\nprint(f"Total pixels: {total_pixels:,}")\nprint(f"Total RGB values: {rgb_values:,}")\n\n# Try these tools from your syllabus:\n# Create pixel art:  piskelapp.com\n# Explore RGB:       w3schools.com/colors/colors_rgb.asp\n# See CV live:       emojiscavengerhunt.withgoogle.com`,
    keyPoints:['Computer Vision = AI that sees and understands images and video','Pixel = smallest unit of a digital image','Resolution = width × height (total pixel count)','Grayscale image: each pixel = ONE value (0 = black, 255 = white)','RGB image: each pixel = THREE values (R, G, B) each from 0 to 255','Black=(0,0,0), White=(255,255,255), Red=(255,0,0)'],
    tips:['RGB(255,0,0)=Red, (0,255,0)=Green, (0,0,255)=Blue — memorise these','Higher resolution = more pixels = more data = more processing needed','Grayscale = 1 channel (simpler), RGB = 3 channels (colour)'],
    commonMistakes:['Thinking RGB values go from 0-100 — they go from 0-255','Saying all images are RGB — grayscale images have only 1 channel','Confusing resolution (number of pixels) with image quality or sharpness'],
  },
  {
    title:'CNN — Convolutional Neural Network Architecture',
    subject:'AI', class:'X', unit:'Unit 4: Computer Vision', topic:'CNN Architecture',
    difficulty:'Advanced', order:36, isPublished:true,
    content:`## What is CNN?\n**Convolutional Neural Network** — a special neural network designed for **processing images**. It automatically learns to extract features from images without manual programming.\n\n## Why CNN Instead of Regular Neural Network?\n- Regular NN treats each pixel independently → too many connections → very slow\n- CNN uses local connections — each neuron looks at a small area\n- Much more efficient for images\n- Automatically learns: edges → shapes → parts → whole objects\n\n## CNN Architecture — 4 Main Layers\n\n### 1. Convolutional Layer\n- Applies **filters (kernels)** to the input image\n- Each filter detects ONE type of feature (edge, curve, color patch)\n- Output of applying a filter = **Feature Map**\n- Multiple filters → multiple feature maps\n\n### 2. Pooling Layer (Subsampling)\n- **Reduces the size** of feature maps\n- **Max Pooling** — takes the maximum value from each small region\n- Benefits: faster processing, less memory, reduces overfitting\n\n### 3. Fully Connected Layer\n- Regular neural network layer\n- Takes flattened feature maps as input\n- Combines all learned features to make final decision\n\n### 4. Output Layer\n- Final predictions\n- Number of neurons = number of output classes\n\n## Convolution Operation\nA **kernel/filter** is a small matrix (e.g., 3×3 or 5×5).\nIt slides over the image step by step.\nAt each position: multiply each element × kernel value, then sum them all.\nResult = one number in the feature map.\n\n## What CNN Learns Layer by Layer\n- **Layer 1:** Edges and lines\n- **Layer 2:** Shapes and curves\n- **Layer 3:** Object parts (eyes, wheels)\n- **Layer 4+:** Complete objects (face, car)`,
    syntax:`# Convolution operation — manual example:\nimage_patch = [[1, 2, 3],\n               [4, 5, 6],\n               [7, 8, 9]]\n\nedge_kernel = [[-1, -1, -1],\n               [-1,  8, -1],\n               [-1, -1, -1]]\n\n# Multiply element-wise then sum:\nresult = 0\nfor i in range(3):\n    for j in range(3):\n        result += image_patch[i][j] * edge_kernel[i][j]\nprint("Convolution result:", result)\n\n# CNN processing flow for image classification:\n# Input Image (e.g., 64×64 RGB = 3 channels)\n#   ↓\n# Conv Layer 1: 32 filters of size 3×3\n#               → detects edges and basic shapes\n#   ↓\n# Max Pooling:  reduces 64×64 → 32×32 (half the size)\n#   ↓\n# Conv Layer 2: 64 filters of size 3×3\n#               → detects more complex shapes and patterns\n#   ↓\n# Max Pooling:  reduces 32×32 → 16×16\n#   ↓\n# Flatten:      convert 2D maps to 1D vector\n#   ↓\n# Fully Connected Layer\n#   ↓\n# Output: [Cat: 90%, Dog: 10%] → predicted class = Cat\n\n# Try these interactive tools:\n# Image kernels:     setosa.io/ev/image-kernels/\n# Build classifier:  teachablemachine.withgoogle.com`,
    keyPoints:['CNN designed specifically for processing image data','Convolutional Layer: applies filters/kernels to detect features in image','Kernel/Filter: small matrix that slides over image to detect features','Feature Map: output produced after applying one filter to image','Max Pooling: reduces size by taking maximum value from each region','Fully Connected Layer: combines all features to make final prediction'],
    tips:['Think of CNN learning as: edges → shapes → parts → whole objects','More convolutional layers = can detect more complex and abstract features','Pooling reduces image dimensions → faster processing and less memory','Try setosa.io/ev/image-kernels/ to see different kernel effects on images'],
    commonMistakes:['Confusing Kernel/Filter (small matrix) with Layer (a stage in CNN)','Thinking CNN only works for classification — also used for detection and segmentation','Forgetting that Max Pooling reduces the size of feature maps','Confusing Feature Map (output) with Kernel (the filter itself)'],
  },
  {
    title:'AI Ethics — Bias Transparency Privacy Bioethics Frameworks',
    subject:'AI', class:'X', unit:'Unit 1: AI Ethics', topic:'Ethical Frameworks of AI',
    difficulty:'Basic', order:37, isPublished:true,
    content:`## Why AI Ethics?\nAI makes decisions that directly affect people's lives — jobs, loans, healthcare, justice. It must be **fair, transparent, safe, and accountable**.\n\n## Key Ethical Concerns\n\n### 1. Bias\n- AI model treats different groups of people **unfairly**\n- Root cause: biased or unrepresentative training data\n- Example: Hiring AI trained on historical data may discriminate against women\n- Example: Face recognition works much better for lighter skin tones\n- Solution: Use diverse, balanced, and representative training data\n\n### 2. Transparency\n- People should understand **how AI makes decisions** that affect them\n- Problem: "Black box" AI cannot explain its reasoning\n- Solution: Explainable AI (XAI) — AI that can explain its decisions\n\n### 3. Privacy\n- AI systems collect and use large amounts of personal data\n- Must protect individual privacy and prevent misuse\n\n### 4. Accuracy\n- AI must be tested thoroughly before deployment in critical applications\n- Medical AI must be highly accurate — wrong decisions can cost lives\n\n### 5. Accountability\n- When AI makes a harmful mistake — who is responsible?\n- Developer? Company? User? Government?\n\n## Ethical Frameworks\n1. **Consequentialism** — Judge by outcomes: good results justify the means\n2. **Deontology** — Follow fixed rules and duties regardless of outcome\n3. **Virtue Ethics** — Act with good character and moral values\n4. **Bioethics** — Special framework for medical and biological contexts\n\n## Bioethics — Four Core Principles\n- **Beneficence** — Do good, help patients\n- **Non-maleficence** — Avoid harm (First, do no harm)\n- **Autonomy** — Patient has the right to decide their own treatment\n- **Justice** — All patients treated fairly regardless of background`,
    syntax:`# Bias detection example:\n# Face recognition trained mostly on light-skinned faces\n# Works great for some groups, poorly for others → BIASED!\n\ndef check_bias(predictions, actual, groups):\n    for group in set(groups):\n        indices = [i for i, g in enumerate(groups) if g == group]\n        correct = sum(1 for i in indices if predictions[i] == actual[i])\n        accuracy = correct / len(indices) * 100\n        print(f"Group {group}: {accuracy:.1f}% accuracy")\n# If different groups get very different accuracy → BIASED!\n\n# Transparency example:\n# BAD  (Black Box): "Loan REJECTED." — no explanation\n# GOOD (Explainable): "Loan REJECTED because:\n#   - Monthly income below minimum (40% reason)\n#   - No existing credit history (35% reason)\n#   - High existing debt ratio (25% reason)"\n\n# Privacy example:\n# AI should not store sensitive data unnecessarily\n# Use anonymized data for model training when possible\n\n# Bioethics principle mnemonic: BNAJ\n# B = Beneficence     (do good)\n# N = Non-maleficence (avoid harm)\n# A = Autonomy        (patient decides)\n# J = Justice         (treat all fairly)`,
    keyPoints:['Bias: AI unfair to groups — caused by biased or unrepresentative training data','Transparency: people should understand how AI made a decision affecting them','Privacy: AI must protect personal data and prevent misuse','Accountability: clear responsibility needed when AI causes harm','Bioethics: Beneficence, Non-maleficence, Autonomy, Justice','Diverse training data is the solution to reducing AI bias'],
    tips:['Bias comes from data quality — garbage in, garbage out','Transparency = ability to explain AI decisions clearly','Bioethics mnemonic: BNAJ (Beneficence, Non-maleficence, Autonomy, Justice)','High accuracy does NOT mean the model is bias-free'],
    commonMistakes:['Confusing bias (unfair groups) with inaccuracy (wrong predictions)','Thinking transparency means showing the source code — it means explaining decisions','Assuming a highly accurate model cannot be biased — it can be!'],
  },
]

const QUESTIONS = [
  // Python Functions
  { class:'XII', subject:'Python', topic:'Functions', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which keyword is used to define a function in Python?', options:['fun','function','def','define'], correctAnswer:'def', hint:'It is a 3-letter keyword', explanation:'Python uses def keyword to define all functions' },
  { class:'XII', subject:'Python', topic:'Functions', questionType:'TrueFalse', difficulty:'Easy', marks:1, question:'A function can return multiple values in Python.', options:['True','False'], correctAnswer:'True', hint:'Think about tuples', explanation:'Python returns multiple values as a tuple: return a, b' },
  { class:'XII', subject:'Python', topic:'Functions', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What does a function return when there is no return statement?', options:['0','""','None','Error'], correctAnswer:'None', hint:'Python returns a special value by default', explanation:'All Python functions return None by default if no return statement exists' },
  { class:'XII', subject:'Python', topic:'Functions', questionType:'MCQ', difficulty:'Medium', marks:2, question:'def f(x=5): return x*2 — What is the output of f()?', options:['5','10','Error','0'], correctAnswer:'10', hint:'Default value of x is 5', explanation:'f() uses default x=5, returns 5*2 = 10' },
  // Exception Handling
  { class:'XII', subject:'Python', topic:'Exception Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which block ALWAYS executes in try-except-finally?', options:['try','except','finally','All of them'], correctAnswer:'finally', hint:'One block is guaranteed to always run', explanation:'finally always runs whether an exception occurred or not' },
  { class:'XII', subject:'Python', topic:'Exception Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What exception is raised when dividing any number by zero?', options:['ValueError','TypeError','ZeroDivisionError','MathError'], correctAnswer:'ZeroDivisionError', hint:'The name describes the error', explanation:'Python raises ZeroDivisionError for division by zero' },
  { class:'XII', subject:'Python', topic:'Exception Handling', questionType:'TrueFalse', difficulty:'Medium', marks:1, question:'The finally block runs ONLY when an exception occurs.', options:['True','False'], correctAnswer:'False', hint:'Finally means always', explanation:'finally always runs — with or without any exception' },
  // File Handling
  { class:'XII', subject:'Python', topic:'File Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which file mode opens a file for reading only in Python?', options:['"w"','"r"','"a"','"rb"'], correctAnswer:'"r"', hint:'r stands for read', explanation:'Mode "r" opens file for reading only; file must already exist' },
  { class:'XII', subject:'Python', topic:'File Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which file mode will DELETE all existing content when opening?', options:['"r"','"a"','"w"','"r+"'], correctAnswer:'"w"', hint:'This mode is dangerous with existing files', explanation:'"w" mode erases all existing content and creates/overwrites the file' },
  { class:'XII', subject:'Python', topic:'File Handling', questionType:'MCQ', difficulty:'Medium', marks:2, question:'Which method reads ALL lines and returns them as a LIST?', options:['read()','readline()','readlines()','readall()'], correctAnswer:'readlines()', hint:'The plural form of readline', explanation:'readlines() returns a list where each element is one line including newline character' },
  // Stack
  { class:'XII', subject:'Python', topic:'Stack', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What does LIFO stand for in the context of Stack?', options:['Last In First Out','Last In First Order','Linear In First Out','List In File Out'], correctAnswer:'Last In First Out', hint:'Think of stacking plates — last placed is first removed', explanation:'LIFO = Last In First Out is the fundamental principle of Stack' },
  { class:'XII', subject:'Python', topic:'Stack', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which Python list method is used for the PUSH operation in Stack?', options:['insert()','add()','append()','push()'], correctAnswer:'append()', hint:'It adds element to the end of list', explanation:'append() adds to end of list which represents the top of stack = PUSH operation' },
  { class:'XII', subject:'Python', topic:'Stack', questionType:'MCQ', difficulty:'Medium', marks:2, question:'Stack contains [10, 20, 30] with 30 on top. What does pop() return?', options:['10','20','30','[10,20]'], correctAnswer:'30', hint:'LIFO — last element added is first removed', explanation:'pop() removes and returns the top element which is 30 (last added)' },
  // Binary Files
  { class:'XII', subject:'Python', topic:'Binary File Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which Python module is used for binary file operations?', options:['binary','struct','pickle','file'], correctAnswer:'pickle', hint:'It is named after a preservation method', explanation:'pickle module is used to serialize Python objects to binary files' },
  { class:'XII', subject:'Python', topic:'Binary File Handling', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which function writes a Python object to a binary file?', options:['write()','save()','dump()','store()'], correctAnswer:'dump()', hint:'Rhymes with pump', explanation:'pickle.dump(object, file) serializes and writes object to binary file' },
  // SQL
  { class:'XII', subject:'Database', topic:'SQL', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which SQL command retrieves data from a table?', options:['GET','FETCH','SELECT','RETRIEVE'], correctAnswer:'SELECT', hint:'Starts with S, most used SQL command', explanation:'SELECT is the SQL command used to retrieve/query data from tables' },
  { class:'XII', subject:'Database', topic:'SQL', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which SQL clause is used to filter rows based on a condition?', options:['FILTER','HAVING','WHERE','LIMIT'], correctAnswer:'WHERE', hint:'Comes after FROM in a SELECT statement', explanation:'WHERE clause filters rows based on specified condition' },
  { class:'XII', subject:'Database', topic:'SQL', questionType:'MCQ', difficulty:'Medium', marks:2, question:'Which aggregate function returns the total number of rows?', options:['SUM()','AVG()','COUNT()','TOTAL()'], correctAnswer:'COUNT()', hint:'The name describes exactly what it does', explanation:'COUNT() returns the number of rows matching the given condition' },
  { class:'XII', subject:'Database', topic:'SQL', questionType:'TrueFalse', difficulty:'Easy', marks:1, question:'A PRIMARY KEY column can contain NULL values.', options:['True','False'], correctAnswer:'False', hint:'Primary key must be unique and identify every row', explanation:'PRIMARY KEY cannot have NULL values — it must uniquely identify every row' },
  { class:'XII', subject:'Database', topic:'SQL', questionType:'MCQ', difficulty:'Medium', marks:2, question:'What does ALTER TABLE command do in SQL?', options:['Delete the table','Change table structure','Insert new rows','Select all rows'], correctAnswer:'Change table structure', hint:'ALTER = modify/change', explanation:'ALTER TABLE modifies the structure of existing table: add/drop/modify columns' },
  // Networks
  { class:'XII', subject:'Networks', topic:'Network Devices', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which device connects two different networks and routes packets between them?', options:['Hub','Switch','Router','Repeater'], correctAnswer:'Router', hint:'It routes packets between different networks', explanation:'Router connects different networks and finds the best path for data packets' },
  { class:'XII', subject:'Networks', topic:'Protocols', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What does HTTP stand for?', options:['HyperText Transfer Protocol','High Transfer Text Protocol','HyperText Transport Program','Home Text Transfer Protocol'], correctAnswer:'HyperText Transfer Protocol', hint:'HyperText = web pages, Transfer = sending them', explanation:'HTTP = HyperText Transfer Protocol, used for transferring web pages' },
  { class:'XII', subject:'Networks', topic:'Topologies', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which topology connects all computers to a single CENTRAL hub or switch?', options:['Bus','Ring','Star','Tree'], correctAnswer:'Star', hint:'Looks like a star shape when drawn on paper', explanation:'Star topology has all computers connected to a central hub or switch' },
  { class:'XII', subject:'Networks', topic:'Transmission Media', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which transmission media uses LIGHT pulses to transmit data?', options:['Twisted Pair Cable','Coaxial Cable','Fiber Optic Cable','Radio Waves'], correctAnswer:'Fiber Optic Cable', hint:'It is the fastest transmission media', explanation:'Fiber Optic Cable transmits data as light pulses, not electrical signals' },
  // Class X AI
  { class:'X', subject:'AI', topic:'AI Project Cycle', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What is the FIRST stage of the AI Project Cycle?', options:['Data Acquisition','Problem Scoping','Modelling','Evaluation'], correctAnswer:'Problem Scoping', hint:'You must define the problem before doing anything else', explanation:'Problem Scoping is the first stage — you must clearly define what problem to solve' },
  { class:'X', subject:'AI', topic:'ML Types', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which type of Machine Learning uses labeled training data?', options:['Unsupervised Learning','Reinforcement Learning','Supervised Learning','Deep Learning'], correctAnswer:'Supervised Learning', hint:'Labeled = supervised/guided by correct answers', explanation:'Supervised Learning uses labeled examples (with correct answers) to train models' },
  { class:'X', subject:'AI', topic:'ML Types', questionType:'MCQ', difficulty:'Medium', marks:2, question:'Predicting the price of a house is an example of which ML type?', options:['Classification','Clustering','Regression','Association'], correctAnswer:'Regression', hint:'Output is a numerical value, not a category', explanation:'Regression predicts numerical values like price, temperature, marks' },
  { class:'X', subject:'AI', topic:'Computer Vision', questionType:'MCQ', difficulty:'Easy', marks:1, question:'In a grayscale image, what pixel value represents BLACK?', options:['255','128','0','64'], correctAnswer:'0', hint:'0 = darkest, 255 = brightest', explanation:'Grayscale: 0 = black (no brightness), 128 = gray, 255 = white (full brightness)' },
  { class:'X', subject:'AI', topic:'Computer Vision', questionType:'MCQ', difficulty:'Easy', marks:1, question:'What is the RGB value for pure RED color?', options:['(0,255,0)','(0,0,255)','(255,0,0)','(255,255,0)'], correctAnswer:'(255,0,0)', hint:'First value in RGB is the Red channel', explanation:'RGB (255,0,0) = maximum Red, zero Green, zero Blue = pure Red' },
  { class:'X', subject:'AI', topic:'Neural Networks', questionType:'MCQ', difficulty:'Easy', marks:1, question:'Which layer of CNN applies filters/kernels to detect image features?', options:['Fully Connected Layer','Pooling Layer','Convolutional Layer','Output Layer'], correctAnswer:'Convolutional Layer', hint:'The C in CNN describes this layer', explanation:'Convolutional Layer applies filters/kernels across image to detect features like edges' },
  { class:'X', subject:'AI', topic:'Model Evaluation', questionType:'MCQ', difficulty:'Medium', marks:2, question:'For DISEASE DETECTION, which metric should be highest to ensure no sick patient is missed?', options:['Precision','Accuracy','Recall','F1 Score'], correctAnswer:'Recall', hint:'We must NOT miss any actual positive (sick) patient', explanation:'Recall = TP/(TP+FN). High Recall means we catch almost all actual positive cases (sick patients)' },
  { class:'X', subject:'AI', topic:'AI Ethics', questionType:'MCQ', difficulty:'Easy', marks:1, question:'When an AI model treats different groups of people unfairly, it is said to have:', options:['Low accuracy','Overfitting','Bias','Underfitting'], correctAnswer:'Bias', hint:'Unfair treatment towards certain groups', explanation:'Bias in AI means unfair treatment of different groups, usually caused by unrepresentative training data' },
  { class:'X', subject:'AI', topic:'AI Project Cycle', questionType:'TrueFalse', difficulty:'Easy', marks:1, question:'Data Exploration stage comes BEFORE Modelling in the AI Project Cycle.', options:['True','False'], correctAnswer:'True', hint:'You must understand the data before building a model', explanation:'Correct order is: Problem Scoping → Data Acquisition → Data Exploration → Modelling → Evaluation' },
  { class:'X', subject:'AI', topic:'ML Types', questionType:'TrueFalse', difficulty:'Easy', marks:1, question:'Unsupervised Learning requires labeled training data to learn patterns.', options:['True','False'], correctAnswer:'False', hint:'Unsupervised = no supervision = no labels provided', explanation:'Unsupervised Learning uses UNLABELED data — the model finds patterns completely on its own' },
]

export async function GET() {
  try {
    await connectDB()
    const results = { admin:{ status:'', email:'' }, notes:{ added:0, skipped:0 }, questions:{ added:0, skipped:0 } }

    // ── Create Admin if not exists ──────────────────────────
    const existing = await User.findOne({ role:'admin' })
    if (existing) {
      results.admin = { status:'already_exists', email:existing.email }
    } else {
      const hashed = await bcrypt.hash('Admin@Vidyalaya123', 12)
      const admin = await User.create({ name:'Shivam Tiwari', email:'shivam@vidyalaya.edu', password:hashed, role:'admin', class:'XII', rollNumber:'ADMIN001', isActive:true, createdAt:new Date() })
      results.admin = { status:'created', email:admin.email }
    }

    // ── Seed all Notes ──────────────────────────────────────
    for (const note of NOTES) {
      const exists = await Note.findOne({ title: note.title })
      if (exists) { results.notes.skipped++; continue }
      await Note.create(note)
      results.notes.added++
    }

    // ── Seed all Questions ──────────────────────────────────
    for (const q of QUESTIONS) {
      const exists = await Question.findOne({ question: q.question })
      if (exists) { results.questions.skipped++; continue }
      await Question.create({ ...q, isActive:true })
      results.questions.added++
    }

    return NextResponse.json({
      success: true,
      message: '✅ FULL SETUP COMPLETE! Your platform is 100% ready.',
      summary: {
        admin: results.admin,
        notes_added: results.notes.added,
        notes_skipped: results.notes.skipped,
        questions_added: results.questions.added,
        questions_skipped: results.questions.skipped,
      },
      login_now: {
        url: '/login',
        email: results.admin.status === 'created' ? 'shivam@vidyalaya.edu' : results.admin.email,
        password: results.admin.status === 'created' ? 'Admin@Vidyalaya123' : '(use your existing password)',
      },
      next_steps: [
        '1. Go to /login and sign in with above credentials',
        '2. CHANGE YOUR PASSWORD immediately after first login',
        '3. Go to Admin → Students to add your students',
        '4. All notes are live — students can read them now!',
        '5. Go to Admin → Tests to create your first test',
        '6. IMPORTANT: Delete this file app/api/setup-all/route.js from GitHub!',
      ],
    })
  } catch (error) {
    return NextResponse.json({
      success: false,
      error: error.message,
      fix: 'Check that MONGODB_URI environment variable is correctly set in Vercel dashboard',
      tip: 'Make sure your MongoDB Atlas IP whitelist includes 0.0.0.0/0 (Allow from anywhere)',
    }, { status: 500 })
  }
}
